/*自定义语言fo\he 不知道哪国语言*/
var langarr   = [];
langarr['cn']   = 'zh_CN';    //中文
langarr['en']   = 'LANG';     //英文
langarr['tc']   = 'zh_TW';    //中文繁体
//  langarr['sq']   = '';    //阿尔巴尼亚语
langarr['ar']   = 'ar';    //阿拉伯语
//  langarr['az']   = '';    //阿塞拜疆语
//  langarr['ga']   = '';    //爱尔兰语
//  langarr['et']   = '';    //爱沙尼亚语
//  langarr['be']   = '';    //白俄罗斯语
langarr['bg']   = 'bg';    //保加利亚语
//  langarr['is']   = '';    //冰岛语
langarr['pl']   = 'pl';    //波兰语
langarr['fa']   = 'fa';    //波斯语
//  langarr['af']   = '';    //布尔语(南非荷兰语)
langarr['da']   = 'da';    //丹麦语
langarr['de']   = 'de';    //德语
langarr['ru']   = 'ru';    //俄语
langarr['fr']   = 'fr';    //法语
//  langarr['tl']   = '';    //菲律宾语
//  langarr['fi']   = '';    //芬兰语
//  langarr['ht']   = '';    //海地克里奥尔语
langarr['ko']   = 'ko';    //韩语
langarr['nl']   = 'nl';    //荷兰语
//  langarr['gl']   = '';    //加利西亚语
langarr['ca']   = 'ca';    //加泰罗尼亚语
langarr['cs']   = 'cs';    //捷克语
//  langarr['hr']   = '';    //克罗地亚语
//  langarr['la']   = '';    //拉丁语
//  langarr['lv']   = '';    //拉脱维亚语
//  langarr['lt']   = '';    //立陶宛语
langarr['ro']   = 'ro';    //罗马尼亚语
//  langarr['mt']   = '';    //马耳他语
//  langarr['ms']   = '';    //马来语
//  langarr['mk']   = '';    //马其顿语
langarr['no']   = 'no';    //挪威语
langarr['pt']   = 'pt_BR';    //葡萄牙语[巴西]
langarr['ja']   = 'jp';    //日语
langarr['sv']   = 'sv';    //瑞典语
langarr['sr']   = 'sr';    //塞尔维亚语
langarr['sk']   = 'sk';    //斯洛伐克语
langarr['sl']   = 'sl';    //斯洛文尼亚语
//  langarr['sw']   = '';    //斯瓦希里语
//  langarr['th']   = '';    //泰语
langarr['tr']   = 'tr';    //土耳其语
//  langarr['cy']   = '';    //威尔士语
langarr['uk']   = 'uk';    //乌克兰语
//  langarr['iw']   = '';    //希伯来语
langarr['el']   = 'el';    //希腊语
//  langarr['eu']   = '';    //西班牙的巴斯克语
langarr['es']   = 'es';    //西班牙语
langarr['hu']   = 'hu';    //匈牙利语
langarr['it']   = 'it';    //意大利语
//  langarr['yi']   = '';    //意第绪语
//  langarr['ur']   = '';    //乌尔都语
langarr['id']   = 'id';    //印尼语
langarr['vi']   = 'vi';    //越南语

